services:
  postgres:
    image: postgres:15-alpine
    container_name: dev_postgres
    env_file:
      - .env
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: timlul_app
    ports:
      - "${STREAMLIT_SERVER_PORT:-8501}:8501"
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - postgres

volumes:
  pgdata: